spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/ureshii
    username: postgres
    password: 1234
    hikari:
      maximum-pool-size: 16
      connectionTimeout: 300000
      validation-timeout: 300000

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 22MB

app:
  baseDirectory: /opt/ureshii
  jwt:
    jwtSecret: haraJWTSecretKey
    jwtExpirationMs: 60000000
    jwtRefreshExpirationMs: 1800000000

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG

server:
  servlet:
    context-path=: /ureshii