spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/hara
    username: postgres
    password: hara1234HARA123
    hikari:
      maximum-pool-size: 16
      connectionTimeout: 300000
      validation-timeout: 300000

  jpa:
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 8MB

app:
  baseDirectory: /opt/ureshii
  jwt:
    jwtSecret: haraJWTSecretKey
    jwtExpirationMs: 60000000
    jwtRefreshExpirationMs: 1800000000
